### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by georgesnow** [georgesnow/MacPassRevealer#4]
**_Roadmap for plugin_** 
_Ordering is sort of arbitrary and may change depending on difficulty and time_
Also not sure what is more important to other users

**Follow-up**
_need to follow up with @mstarke about these_
- [x] Need to find out if plug-ins will be supported in main MacPass in future release both Autotype and revealer without GUI prefs ??
- [x] Proper signing and no longer need to use “load insecure plugins option”

**Fixes**
- [x] Use method for activateMacPass in global keyboard shortcut rather then doubling code?

Enhancements 
**Short-term** 
- [x] User preferences GUI - overall
- [x] Option click on menu Menubar icon for additional options prefs
- [x] User defined keyboard shortcut
- [x] Toggle - menu bar or keyboard?? so you could use one or the other (ie keyboard shortcut but no menu bar and vice versa)

**Short-mid term (not sure of possibility)**
- [x] Land focus in search bar when using global keyboard shortcut ... not sure even possible. May need the option exposed in core code of MacPass to allow it?
- [ ] Hide dock icon of MacPass when using Menubar option- core app if detects plugin offers setting or setting from within plugin options..??

**Long-term**
_would be really cool not sure if it will happen_
- [ ] Search from menubar? Lots of dependencies and a lot of work to make this work: query database, XPC messaging, active/context search or have to hit enter?, security?, possibly to incorporate functionally of Autotype ie workspace area. "current active app bundle" specific VPN client is detected when click menu bar and provides a relevant result in the menubar search and can copy from menubar or trigger autotype??

**Comment by mstarke** [comment]
MacPassRevealer looks like something that is worth moving into core MacPass without the need for a plugin. There is a related issue on MacPass asking for "MenuItem" only display without having the app inside the dock so this might be work combining

**Comment by mstarke** [comment]
What you describe here is sort of a project, so you might want to use Github's feature instead of putting everything inside an issue.

**Comment by georgesnow** [comment]
I had a feeling that it was turning into something "more". I did see that thread. It partially inspired the idea to build the plugin. I look into moving this to a project.

I am very new at ObjC. When I though about trying to build the functionality and how to incorporate into the core code it seemed awfully daunting. The plugin worked well because it containerized what i was doing for testing, limiting the impact (breaking other stuff), and troubleshooting. Also it's been helping me with learning ObjC better :) 

If you are ok with it. I would like to refine it a bit further as a plugin. Maybe set a milestone or two? ie reaches certain set of functionality it would be time to move it into the core code. 

 I have done some more testing with the other functionality listed above. You can see it in my latest commit.

**Comment by georgesnow** [comment]
fixed almost all of these. the search from status item is still interesting to me. However, the latest update with landing search context and landing the focus in the search field make some parts of it less needed. Maybe down the road. I discovered I can show the different view controllers in the pop over. Password Generator, list view, and others. Downside is they are new instances not currently opened ones.

**Comment by georgesnow** [comment]
@mstarke update on the hiding of Dock icon. I have tried a number of ways of hiding the dock icon from the plug-in. And after hiding the dock icon. I get a lot of strange behavior when you open more then one window. example would be you have 1 open database and then you open the preferences window. In one case I lost the ability to hide MacPass, in another I couldn't select the preferences window, and different time it broke the hotkey. However, as soon as change it back to show the dock icon all the behavior returns to normal.

I am not sure if thats the plugin or if it's because dock icon is now hidden that it  breaks the first responder chain or delegates. And since  I couldn't get consistent bad behavior it made hard to troubleshoot.

**Comment by mstarke** [comment]
I glossed over the code. I think the best solution might be to spec the behaviour and re-implement it in MacPass with minor (and mayor) changes in the implementation.

**Comment by georgesnow** [comment]
If you want to make a branch and frame out where you want stuff. I can build the basic functionality and features? That way you can curate it to better fit with the core code. Cause I think you are right my code grew in a way that isn’t easy to just import wholesale. Does that work for you?
